### PR TITLE
chore: generate ts declarations

### PR DESCRIPTION
**Pull request by filahf**
> This PR adds a post-build step to the Makefile to generate typescript declaration files.

### CODE REVIEW

**Comment by abernier** [comment]
here we go!

https://github.com/pmndrs/assets/actions/runs/11001540005

**Comment by filahf** [comment]
:crossed_fingers:

**Comment by abernier** [comment]
nope, same error

I reverted for now

**Comment by filahf** [comment]
Yea.. Did it work for you locally?

**Comment by abernier** [comment]
let me try...

**Comment by filahf** [comment]
https://github.com/DefinitelyTyped/DefinitelyTyped/discussions/70562

It seems like we need @types/node as well. I have to call it day but I'll make another PR tomorrow


third time lucky

**Comment by abernier** [comment]
I reproduced the error on my machine, on this PR branch.

Even without installing @types/node (but maybe better to add them too, dunno)

I managed to prevent the error with executing (`--skipLibCheck`):

```sh
$ npx -p typescript tsc dist/**/*.js --declaration --allowJs --emitDeclarationOnly --outDir dist --skipLibCheck
```

**Pull request merged**
